### ISSUE TITLE
Sms's text wrong encoding

### ISSUE THREAD

**Issue by Farkhod** [franzose/laravel-smpp#10]
Hello

Why our sms has unknown encoding like this 䬀漀搀㨀 ㌀㐀㌀㐀?

**Comment by Farkhod** [comment]
Solved!!

We just replaced 

```php
$message = iconv('UTF-8', 'UCS-2', $message);
```

with

 ```php
$message = mb_convert_encoding($message, "UCS-2", "utf8");
```

in **sendSms** method

**Comment by franzose** [comment]
Hello, @Farkhod! I'll make a quick fix.

**Comment by Farkhod** [comment]
> Hello, @Farkhod! I'll make a quick fix.

(bow)

**Comment by franzose** [comment]
Thank you very much, @Farkhod! I've made a new release.
