### ISSUE TITLE
Does't support Laravel 8

### ISSUE THREAD

**Issue by abuamr-gafurov** [franzose/laravel-smpp#14]
Hi.

Can you add Laravel 8 support ?

**Comment by lovelypuspen** [comment]
Hello dev team, I am working on SMPP project, this is the best solution I found on the web, but I can not use this on laravel 8. I am using Xampp on windows, it is throwing errors as below 
`  Problem 1
    - franzose/laravel-smpp[v1.3, ..., 1.3.x-dev] require illuminate/support ^5|^6|^7 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires franzose/laravel-smpp ^1.3 -> satisfiable by franzose/laravel-smpp[v1.3, v1.3.1, v1.3.2, 1.3.x-dev].
![Screenshot (12)](https://user-images.githubusercontent.com/19345184/109337739-6418c980-788d-11eb-81ad-0d8bee68980c.png)
`

**Comment by MyDcode** [comment]
any luck with Laravel 8?

**Comment by franzose** [comment]
@abuamr-gafurov, @lovelypuspen, @MyDcode I've added Laravel 8 support.
