### ISSUE TITLE
Error adding the library

### ISSUE THREAD

**Issue by nasznjoka** [franzose/laravel-smpp#2]
Running on two different serve environment brings the same error 
Problem 1
    - Installation request for franzose/laravel-smpp ^1.0 -> satisfiable by franzose/laravel-smpp[v1.0].
    - franzose/laravel-smpp v1.0 requires php-smpp/php-smpp dev-master -> satisfiable by php-smpp/php-smpp[dev-master] but these conflict with your requirements or minimum-stability

Installation failed, reverting ./composer.json to its original content.

**Comment by franzose** [comment]
@nasznjoka Hi! Did you try to set the `minimum-stability` option to `dev`? If not yet, could you please, do that and show what Composer says on that?
