### ISSUE TITLE
How to listen for sms

### ISSUE THREAD

**Issue by Kreshnik** [franzose/laravel-smpp#3]
Hi there, 

I was wondering how I would listen for an SMS with the package?.

**Comment by franzose** [comment]
@Kreshnik Hi! Do you mean receiving SMSes? Unfortunately, I'm not a guru on SMPP. I have used it just once and dealt only with sending them. I think you could try to extend the package to provide ability to receive messages because SMPP itself (as far as I know) has such functionality.
