### ISSUE TITLE
Do you need a worker to send many sms?

### ISSUE THREAD

**Issue by Arthur-W-White** [franzose/laravel-smpp#4]
Hi,
Here it says you cannot send sms from your website:
[issue 43](https://github.com/onlinecity/php-smpp/issues/43)
They say you could use a [worker]https://github.com/onlinecity/php-smpp-worker).
Does this package support a worker?

What is the recommended setup to queue thousands of sms and send them?

**Comment by franzose** [comment]
@Arthur-W-White Hi! This library is just a thin wrapper around **onlinecity/php-smpp**. I wrote it for one of the websites I was working on. There was no queues set up and all was working fine. I think it all depends on the SMS provider you use. As of queue, I'd use **Redis** or something.
