### ISSUE TITLE
Laravel 5.4 Conflict with requirements and minimum stability

### ISSUE THREAD

**Issue by san4io** [franzose/laravel-smpp#5]
Hello

I've tried to install you package but where is an issue with installation.

```
Problem 1
    - Installation request for franzose/laravel-smpp ^1.0 -> satisfiable by franzose/laravel-smpp[v1.0].
    - franzose/laravel-smpp v1.0 requires php-smpp/php-smpp dev-master -> satisfiable by php-smpp/php-smpp[dev-master] but these conflict with your requirements or minimum-stability.
```

As I understand you composer.json is referencing bad version, because php-smpp, do not have dev-master.
For now I faked composer.json, and added in require block
```
"php-smpp/php-smpp": "dev-master as 1.2"
```

But it would be nice if dependencies would be fixed :)

**Comment by san4io** [comment]
I think and lock should be upgraded. But your speed is superb :)))

**Comment by franzose** [comment]
@san4io whoops, sorry)

**Comment by san4io** [comment]
Sorry for bothering you, but you should create new tag. Because as I can see many people had same issue, and not everyone knows that they should put in json ` "franzose/laravel-smpp": "dev-master",`, and while requiring it with require they get 1.0 which is not compatible. All in all, next month I'll be working with you package and if contribution is accepted and I will have something to contribute  I'll make PR's.
