### ISSUE TITLE
Class 'LaravelSmpp\SmppServiceInterface' not found

### ISSUE THREAD

**Issue by MagentoExp** [franzose/laravel-smpp#6]
"Cannot instantiate interface LaravelSmpp\SmppServiceInterface"

**Comment by elias-alea** [comment]
I have faced the same issue, @franzose I tried to register the provider but it doesn't work.
in fact, when I try publishing it in laravel, "php artisan vendor:publish", laravel does not even list it among the providers to be published

**Comment by tphil** [comment]
> I have faced the same issue, @franzose I tried to register the provider but it doesn't work.
> in fact, when I try publishing it in laravel, "php artisan vendor:publish", laravel does not even list it among the providers to be published

I have the same issue

**Comment by franzose** [comment]
I suppose you've made a workaround already. But just for you to know, it seems that `composer dump-autoload` has to be run manually after installing the package. I can't say for sure why.

**Comment by tphil** [comment]
@franzose not really, it's not working even after `composer dump-autoload`
