### ISSUE TITLE
SmppServiceInterface not working

### ISSUE THREAD

**Issue by mjindal92** [franzose/laravel-smpp#8]
Hello Friends,

When i am calling (SmppServiceInterface $smpp) in my controller it's not working.

Can you please let me know how we can use in my controller ?

Also i am using laravel version 5.8.

Thanks

**Comment by franzose** [comment]
I'm sorry for the late reply. I came across the same issue while checking your request. It seems you have to run `composer dump-autoload` manually after registering the service provider.
